// Daily view shares the reviewed data and the existing detail dialog.
let todayFilter='all';
const expandedToday=new Set();
const todayGroups=[{id:'good',title:'Сейчас в сезоне',desc:'Пик или подходящий сезон для указанного происхождения.',codes:['p','g'],open:true},{id:'annual',title:'Круглый год',desc:'Сезонного перерыва нет. Спелость важнее месяца.',codes:['a'],open:true},{id:'choose',title:'Хранение и теплица',desc:'Свежий тепличный урожай или хранящийся урожай. Оба могут быть вкусными.',codes:['h','t']},{id:'careful',title:'На границе сезона',desc:'Ранний, поздний или неоднородный период.',codes:['b']},{id:'off',title:'Сейчас не сезон',desc:'Вне обычного сезона свежего урожая этого происхождения и типа.',codes:['n']},{id:'unknown',title:'Сезон пока не установлен',desc:'Сведений недостаточно для уверенного статуса.',codes:['u']}];
const tips={p:'Пик сезонного урожая. Хороший ориентир для сезонного вкуса.',g:'Подходящий сезон для этого происхождения.',h:'Урожай из хранения. Хорошее качество возможно и сейчас.',t:'Тепличный урожай. Вкус зависит от сорта и спелости.',a:'Круглогодичный урожай или предложение свежих плодов. Сейчас нет сезонного перерыва.',b:'Граница сезона: многое зависит от сорта и места выращивания.',n:'Обычный сезон свежего урожая ещё не начался или уже закончился.',u:'По месяцу и этому происхождению сезон пока не определён.'};
function yearRoundGreenhouse(r){return r.months.every(s=>s==='t')}
function cardTip(r,s){if(s==='a'&&r.shortInfo)return r.shortInfo;if(s==='t'&&yearRoundGreenhouse(r))return 'Круглогодичный тепличный урожай. Сейчас нет сезонного перерыва.';return tips[s]}
function nowMoscow(){const d=new Date();return {month:Number(new Intl.DateTimeFormat('en',{month:'numeric',timeZone:'Europe/Moscow'}).format(d))-1,label:new Intl.DateTimeFormat('ru',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Moscow'}).format(d)}}
function renderToday(){const now=nowMoscow(),q=norm($('today-search').value.trim()),origin=$('today-origin').value;
$('today-date').textContent=now.label+' · Москва';
let list=DB.rows.filter(r=>(!q||searchText(r).includes(q))&&matchesOrigin(r.origin,origin)&& (todayFilter!=='fav'||favs.has(r.id)) && (todayFilter!=='good'||['p','g','a'].includes(r.months[now.month])||yearRoundGreenhouse(r))&&(todayFilter!=='off'||r.months[now.month]==='n'));
list.sort((a,b)=>(a.months[now.month]==='p'?-1:0)-(b.months[now.month]==='p'?-1:0)||a.name.localeCompare(b.name,'ru')||a.origin.localeCompare(b.origin,'ru'));
$('today-count').textContent='Найдено: '+list.length;
document.querySelectorAll('[data-today-filter]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.todayFilter===todayFilter));
$('today-groups').innerHTML=todayGroups.map(group=>{let rr=list.filter(r=>group.codes.includes(r.months[now.month]));if(!rr.length)return '';const all=expandedToday.has(group.id)||!!q;let visible=all?rr:rr.slice(0,9);return '<details class="shop-group" data-group="'+group.id+'" '+(group.open||q||origin||todayFilter!=='all'||expandedToday.has(group.id)?'open':'')+'><summary>'+group.title+' <span class="group-count">'+rr.length+'</span></summary><p class="group-desc">'+group.desc+'</p><div class="shop-cards">'+visible.map(r=>{const s=r.months[now.month];return '<article class="shop-card"><div class="shop-card-top">'+pill(s)+'<button class="fav" data-today-fav="'+r.id+'" aria-pressed="'+favs.has(r.id)+'" aria-label="'+(favs.has(r.id)?'Убрать из избранного: ':'В избранное: ')+esc(r.name+', '+r.origin)+'">'+(favs.has(r.id)?'♥':'♡')+'</button></div><h3><button data-today-detail="'+r.id+'">'+esc(r.name)+'</button></h3><p class="shop-origin">'+esc(r.origin)+'</p><p class="shop-tip">'+esc(cardTip(r,s))+'</p><button class="why" data-today-detail="'+r.id+'">Подробнее →</button></article>'}).join('')+'</div>'+(!all&&rr.length>9?'<button class="show-more" data-more="'+group.id+'">Показать остальные: '+(rr.length-9)+'</button>':'')+'</details>'}).join('')||'<div class="empty">'+(todayFilter==='fav'?'В избранном пока ничего нет по этому запросу. Добавляйте продукты сердечком.':'Ничего не найдено. Попробуйте другое название или сбросьте фильтры.')+'</div>';
}
$('today-origin').innerHTML=originOptions();
$('today-search').addEventListener('input',renderToday);$('today-origin').addEventListener('change',renderToday);
document.querySelectorAll('[data-today-filter]').forEach(b=>b.onclick=()=>{todayFilter=b.dataset.todayFilter;renderToday()});
$('today-reset').onclick=()=>{$('today-search').value='';$('today-origin').value='';todayFilter='all';expandedToday.clear();renderToday()};
$('today-groups').onclick=e=>{const d=e.target.closest('[data-today-detail]'),f=e.target.closest('[data-today-fav]'),more=e.target.closest('[data-more]');if(d)details(d.dataset.todayDetail,nowMoscow().month);if(f){favs.has(f.dataset.todayFav)?favs.delete(f.dataset.todayFav):favs.add(f.dataset.todayFav);saveStore('moscow-season-favorites-v2',[...favs]);const openGroups=[...document.querySelectorAll('.shop-group[open]')].map(el=>el.dataset.group);update();renderToday();for(const id of openGroups){const el=document.querySelector('[data-group="'+id+'"]');if(el)el.open=true;}const focus=document.querySelector('[data-today-fav="'+f.dataset.todayFav+'"]');if(focus)focus.focus();}if(more){expandedToday.add(more.dataset.more);renderToday()}};
document.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='today')renderToday()}));
document.addEventListener('visibilitychange',()=>{if(!document.hidden)renderToday()});
let displayedDate=nowMoscow().label;
setInterval(()=>{const next=nowMoscow().label;if(!document.hidden&&next!==displayedDate){displayedDate=next;renderToday()}},60000);
renderToday();
